#!/usr/bin/env python3
"""
generate_lists.py
Builds list articles of office holders from the `offices` field of person
articles, and writes them to Lists/.

Which offices get a list is set by the register in
"00 - Meta/Titles and offices.md". A registered office gets its list article
once MIN_HOLDERS different people hold it; below that, no article exists.

Lists/ belongs to this script. A file there that carries the SENTINEL line
and was not produced by the current run is deleted, so a list disappears
when its office drops below the threshold or leaves the register. Files
without the sentinel are never touched.
"""

import os
import re
import sys
import yaml
from pathlib import Path

# ── Configuration ────────────────────────────────────────────────────────────

VAULT_ROOT = Path(os.environ.get("VAULT_ROOT", "."))
REGISTER   = VAULT_ROOT / "00 - Meta" / "Titles and offices.md"
LISTS_DIR  = VAULT_ROOT / "Lists"
MIN_HOLDERS = 3

SENTINEL = ("%% Generated by generate_lists.py from the offices field of person "
            "articles. Edit those articles, not this file. %%")

# Skipped at any depth.
SKIP_DIRS = {".git", ".github", ".githooks", ".obsidian", "_fileClasses", "_templates", "node_modules"}
# Skipped only at the vault root. Other folders named "Lists" exist deeper in
# the vault (Philosophy/Politics/Lists) and are ordinary articles.
SKIP_TOP = {"00 - Meta", LISTS_DIR.name}

FRONTMATTER_RE = re.compile(r"^---[ \t]*\r?\n(.*?)\r?\n---[ \t]*(?:\r?\n|$)", re.DOTALL)
YAML_BLOCK_RE  = re.compile(r"^```ya?ml[ \t]*\r?\n(.*?)\r?\n```", re.DOTALL | re.MULTILINE)
WIKILINK_RE    = re.compile(r"\[\[(?:[^\]|]*\|)?([^\]]*)\]\]")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _has(value) -> bool:
    if value is None:
        return False
    if isinstance(value, str):
        return bool(value.strip())
    if isinstance(value, (list, tuple, set)):
        return any(_has(v) for v in value)
    if isinstance(value, dict):
        return any(_has(v) for v in value.values())
    return True


def _year(value):
    if isinstance(value, bool) or value is None:
        return None
    s = str(value).strip()
    return int(s) if s.lstrip("-").isdigit() else None


def _key(text) -> str:
    """Matching key: wikilinks reduced to their display text, case folded."""
    return WIKILINK_RE.sub(r"\1", str(text)).strip().casefold()


def _wl(value) -> str:
    """Wikilink a value, or join a list of them. "" when empty."""
    if isinstance(value, (list, tuple, set)):
        parts = [_wl(v) for v in value if _has(v)]
        return ", ".join(parts)
    if not _has(value):
        return ""
    s = str(value).strip()
    return s if s.startswith("[[") else f"[[{s}]]"


def _cell(text: str) -> str:
    """Make text safe inside a table cell. A pipe inside a wikilink alias
    must be escaped or it splits the cell."""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _is_election(appointer) -> bool:
    return _has(appointer) and "election" in str(appointer).lower()


def read_frontmatter(path: Path) -> dict:
    try:
        text = path.read_text(encoding="utf-8-sig", errors="replace")
    except OSError as e:
        print(f"warning: could not read {path}: {e}", file=sys.stderr)
        return {}
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    try:
        fm = yaml.safe_load(m.group(1))
    except yaml.YAMLError as e:
        first = str(e).splitlines()[0] if str(e) else type(e).__name__
        print(f"warning: skipped {path}, frontmatter will not parse: {first}", file=sys.stderr)
        return {}
    return fm if isinstance(fm, dict) else {}


# ── Register ──────────────────────────────────────────────────────────────────

def load_register() -> list[dict]:
    """Return the registered offices, each with a set of matching keys."""
    try:
        text = REGISTER.read_text(encoding="utf-8-sig")
    except OSError:
        print(f"warning: no register at {REGISTER}; no lists generated", file=sys.stderr)
        return []
    m = YAML_BLOCK_RE.search(text)
    if not m:
        print(f"warning: {REGISTER} has no ```yaml block; no lists generated", file=sys.stderr)
        return []
    try:
        data = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError as e:
        print(f"error: register will not parse: {str(e).splitlines()[0]}", file=sys.stderr)
        sys.exit(1)

    offices, seen_lists, seen_keys = [], set(), {}
    for entry in data.get("offices") or []:
        if not isinstance(entry, dict) or not _has(entry.get("name")) or not _has(entry.get("list")):
            print(f"warning: register entry needs name and list, skipped: {entry!r}", file=sys.stderr)
            continue
        name = str(entry["name"]).strip()
        list_title = str(entry["list"]).strip()
        if list_title in seen_lists:
            print(f"warning: two register entries write {list_title!r}; second skipped", file=sys.stderr)
            continue
        keys = {_key(name)} | {_key(f) for f in (entry.get("formerly") or []) if _has(f)}
        clash = keys & set(seen_keys)
        if clash:
            print(f"warning: {name!r} shares a name with {seen_keys[next(iter(clash))]!r}; "
                  f"second entry skipped", file=sys.stderr)
            continue
        for k in keys:
            seen_keys[k] = name
        seen_lists.add(list_title)
        kind = str(entry.get("kind") or "seat").strip().lower()
        if kind not in ("seat", "membership"):
            print(f"warning: {name!r} has unknown kind {kind!r}; treated as seat", file=sys.stderr)
            kind = "seat"
        offices.append({
            "name": name,
            "list": list_title,
            "kind": kind,
            "keys": keys,
            "summary": str(entry.get("summary") or f"Holders of the office of {name}.").strip(),
            "era": [e for e in (entry.get("era") or []) if _has(e)],
            "tags": [t for t in (entry.get("tags") or []) if _has(t)],
            "holdings": [],
        })
    return offices


# ── Collection ────────────────────────────────────────────────────────────────

def collect(offices: list[dict]) -> None:
    by_key = {k: o for o in offices for k in o["keys"]}
    for md in sorted(VAULT_ROOT.rglob("*.md")):
        rel = md.relative_to(VAULT_ROOT)
        if any(part in SKIP_DIRS for part in rel.parts) or rel.parts[0] in SKIP_TOP:
            continue
        fm = read_frontmatter(md)
        if fm.get("type") != "person":
            continue
        for entry in fm.get("offices") or []:
            if not isinstance(entry, dict) or not _has(entry.get("title")):
                continue
            office = by_key.get(_key(entry["title"]))
            if office is None:
                continue
            office["holdings"].append({
                "holder":    md.stem,
                "start":     _year(entry.get("start_year")),
                "end":       _year(entry.get("end_year")),
                "party":     _wl(entry.get("parties")),
                "appointer": entry.get("appointer"),
                "notes":     str(entry.get("notes")).strip() if _has(entry.get("notes")) else "",
            })


# ── Rendering ─────────────────────────────────────────────────────────────────

def _term(h) -> str:
    start = h["start"] if h["start"] is not None else "?"
    end = h["end"] if h["end"] is not None else "?"
    return f"{start} - {end}"


def render(office: dict) -> str:
    # Dated terms in order; undated ones last, so they are visible but do not
    # distort the order or the numbering.
    dated = sorted((h for h in office["holdings"] if h["start"] is not None),
                   key=lambda h: (h["start"], h["end"] if h["end"] is not None else 10**9, h["holder"]))
    undated = sorted((h for h in office["holdings"] if h["start"] is None),
                     key=lambda h: h["holder"])

    # Overlaps between different holders are shown, not resolved: two holders
    # of a seat at once is either a dispute or a data error, and either way
    # the article is where it gets settled.
    if office["kind"] == "seat":
        for h in dated:
            others = sorted({o["holder"] for o in dated
                             if o["holder"] != h["holder"]
                             and o["start"] < (h["end"] if h["end"] is not None else 10**9)
                             and h["start"] < (o["end"] if o["end"] is not None else 10**9)})
            if others:
                note = "Overlaps " + ", ".join(f"[[{o}]]" for o in others)
                h["notes"] = f"{h['notes']}. {note}" if h["notes"] else note

    rows_src = dated + undated
    appointers = [h["appointer"] for h in rows_src if _has(h["appointer"])]
    show_party = any(h["party"] for h in rows_src)
    show_appt  = bool(appointers)
    appt_head  = "Election" if appointers and all(_is_election(a) for a in appointers) else "Appointed by"
    show_notes = any(h["notes"] for h in rows_src)

    head = (["No."] if office["kind"] == "seat" else []) + ["Name", "Term"]
    head += (["Party"] if show_party else []) + ([appt_head] if show_appt else [])
    head += ["Notes"] if show_notes else []

    rows = []
    number, prev_holder, prev_end = 0, None, None
    for h in rows_src:
        # A gap between one term's end and the next term's start is a vacancy.
        if (office["kind"] == "seat" and h["start"] is not None
                and prev_end is not None and h["start"] > prev_end):
            vac = ([""] if office["kind"] == "seat" else []) + ["*Vacant*", f"{prev_end} - {h['start']}"]
            vac += ([""] if show_party else []) + ([""] if show_appt else []) + ([""] if show_notes else [])
            rows.append(vac)

        cells = []
        if office["kind"] == "seat":
            # A new number for each change of holder; consecutive terms of the
            # same person share one, shown as "-".
            if h["start"] is None:
                cells.append("")
            elif h["holder"] != prev_holder:
                number += 1
                cells.append(str(number))
            else:
                cells.append("-")
        cells += [f"[[{h['holder']}]]", _term(h)]
        if show_party:
            cells.append(h["party"])
        if show_appt:
            cells.append(_wl(h["appointer"]))
        if show_notes:
            cells.append(h["notes"])
        rows.append([_cell(c) for c in cells])

        if h["start"] is not None:
            prev_holder = h["holder"]
            end = h["end"] if h["end"] is not None else h["start"]
            prev_end = end if prev_end is None else max(prev_end, end)

    table = ["| " + " | ".join(head) + " |",
             "| " + " | ".join(":-:" if c in ("No.", "Term") else "---" for c in head) + " |"]
    table += ["| " + " | ".join(r) + " |" for r in rows]

    intro = (f"Holders of the office of {office['name']}, in order of taking office."
             if office["kind"] == "seat" else
             f"Holders of the office of {office['name']}, in order of taking office. "
             f"Several people hold it at the same time.")
    body = "\n".join([intro, "", SENTINEL, "", *table, ""])

    # meta.stub follows the checker's own rule, so a short list is not
    # reported as a finished article with too little text.
    words = len(re.findall(r"\w+", body))

    def ylist(key, values):
        return [f"{key}:"] + ([f"  - {v}" for v in values] if values else ["  -"])

    fm = ["---", "type: index", f"summary: {office['summary']}", "aliases:", "  -"]
    fm += ylist("era", office["era"]) + ylist("tags", office["tags"])
    fm += ["meta:", f"  stub: {'true' if words < 80 else 'false'}", "  verified: false",
           "  image: null", "---", ""]
    return "\n".join(fm) + body


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    offices = load_register()
    collect(offices)

    LISTS_DIR.mkdir(exist_ok=True)
    written = set()
    for office in offices:
        holders = {h["holder"] for h in office["holdings"]}
        if len(holders) < MIN_HOLDERS:
            print(f"  {office['name']}: {len(holders)} holder(s), below {MIN_HOLDERS}, no list")
            continue
        path = LISTS_DIR / f"{office['list']}.md"
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(render(office))
        written.add(path.resolve())
        print(f"  {office['name']}: {len(holders)} holders -> Lists/{path.name}")

    for path in sorted(LISTS_DIR.glob("*.md")):
        if path.resolve() in written:
            continue
        try:
            owned = SENTINEL in path.read_text(encoding="utf-8-sig", errors="replace")
        except OSError:
            owned = False
        if owned:
            path.unlink()
            print(f"  removed Lists/{path.name}: no longer generated")
        else:
            print(f"warning: Lists/{path.name} was not written by this script; left alone",
                  file=sys.stderr)

    print(f"Lists written: {len(written)}.")


if __name__ == "__main__":
    main()
