#!/usr/bin/env python3
"""
generate_lists.py
Builds list articles of office holders from the `offices` field of person
articles, and writes them to Lists/.

Which offices get a list is set by the register in
"00 - Meta/Titles and offices.md". A registered office gets its list article
once MIN_HOLDERS different people hold it; below that, no article exists.

Lists/ belongs to this script. A file there that carries the SENTINEL line
and was not produced by the current run is deleted, so a list disappears
when its office drops below the threshold or leaves the register. Files
without the sentinel are never touched.
"""

import os
import re
import sys
import yaml
from pathlib import Path

# ── Configuration ────────────────────────────────────────────────────────────

VAULT_ROOT = Path(os.environ.get("VAULT_ROOT", "."))
LISTS_DIR  = VAULT_ROOT / "Lists"          # retired: emptied of what this script used to own

OLD_SENTINEL = ("%% Generated by generate_lists.py from the offices field of person "
                "articles. Edit those articles, not this file. %%")
START = "%% holders:start %%"
END   = "%% holders:end %%"

# Skipped at any depth.
SKIP_DIRS = {".git", ".github", ".githooks", ".obsidian", "_fileClasses", "_templates", "node_modules"}
# Skipped only at the vault root. Other folders named "Lists" exist deeper in
# the vault (Philosophy/Politics/Lists) and are ordinary articles.
SKIP_TOP = {"00 - Meta", LISTS_DIR.name}

FRONTMATTER_RE = re.compile(r"^---[ \t]*\r?\n(.*?)\r?\n---[ \t]*(?:\r?\n|$)", re.DOTALL)
YAML_BLOCK_RE  = re.compile(r"^```ya?ml[ \t]*\r?\n(.*?)\r?\n```", re.DOTALL | re.MULTILINE)
WIKILINK_RE    = re.compile(r"\[\[(?:[^\]|]*\|)?([^\]]*)\]\]")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _has(value) -> bool:
    if value is None:
        return False
    if isinstance(value, str):
        return bool(value.strip())
    if isinstance(value, (list, tuple, set)):
        return any(_has(v) for v in value)
    if isinstance(value, dict):
        return any(_has(v) for v in value.values())
    return True


def _year(value):
    if isinstance(value, bool) or value is None:
        return None
    s = str(value).strip()
    return int(s) if s.lstrip("-").isdigit() else None


def _key(text) -> str:
    """Matching key: wikilinks reduced to their display text, case folded."""
    return WIKILINK_RE.sub(r"\1", str(text)).strip().casefold()


def _wl(value) -> str:
    """Wikilink a value, or join a list of them. "" when empty."""
    if isinstance(value, (list, tuple, set)):
        parts = [_wl(v) for v in value if _has(v)]
        return ", ".join(parts)
    if not _has(value):
        return ""
    s = str(value).strip()
    return s if s.startswith("[[") else f"[[{s}]]"


def _cell(text: str) -> str:
    """Make text safe inside a table cell. A pipe inside a wikilink alias
    must be escaped or it splits the cell."""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _is_election(appointer) -> bool:
    return _has(appointer) and "election" in str(appointer).lower()


def read_frontmatter(path: Path) -> dict:
    try:
        text = path.read_text(encoding="utf-8-sig", errors="replace")
    except OSError as e:
        print(f"warning: could not read {path}: {e}", file=sys.stderr)
        return {}
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    try:
        fm = yaml.safe_load(m.group(1))
    except yaml.YAMLError as e:
        first = str(e).splitlines()[0] if str(e) else type(e).__name__
        print(f"warning: skipped {path}, frontmatter will not parse: {first}", file=sys.stderr)
        return {}
    return fm if isinstance(fm, dict) else {}


# ── Titles and their holders ──────────────────────────────────────────────────

INTERLUDE_LABELS = {
    "regency":   "Regency",
    "disputed":  "Disputed succession",
    "vacant":    "Vacancy",
    "abolished": "Abolition",
    "other":     "Interlude",
}
BIG = 10**6


def _text(value) -> str:
    """Plain text, or "" if empty."""
    return str(value).strip() if _has(value) else ""


def _name(value) -> str:
    """"[[Target|Label]]" or "Target" as the bare target name."""
    if not _has(value):
        return ""
    s = str(value).strip()
    m = re.fullmatch(r"\[\[([^\]]+)\]\]", s)
    if m:
        s = m.group(1).split("|")[0]
    return s.strip()


def load_titles() -> dict:
    """path -> title article, for every note with type: title."""
    titles = {}
    for md in sorted(VAULT_ROOT.rglob("*.md")):
        rel = md.relative_to(VAULT_ROOT)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        fm = read_frontmatter(md)
        if fm.get("type") == "title":
            fm = dict(fm)
            fm["path"] = md
            fm["name"] = md.stem
            fm["holdings"] = []
            titles[md.stem] = fm
    return titles


def collect(titles: dict) -> list[str]:
    """Read every person's titles into the title they belong to."""
    problems = []
    for md in sorted(VAULT_ROOT.rglob("*.md")):
        rel = md.relative_to(VAULT_ROOT)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        fm = read_frontmatter(md)
        if fm.get("type") != "person":
            continue
        for entry in fm.get("titles") or []:
            if not isinstance(entry, dict) or not _has(entry.get("title")):
                continue
            name = _name(entry["title"])
            title = titles.get(name)
            if title is None:
                problems.append(f"{md.stem}: no title article for [[{name}]]")
                continue
            seat = _name(entry.get("seat"))
            if title.get("seats") and not seat:
                problems.append(f"{md.stem}: [[{name}]] is split by place but the entry has no seat")
            title["holdings"].append({
                "holder":    md.stem,
                "seat":      seat,
                "start":     _year(entry.get("start_year")),
                "end":       _year(entry.get("end_year")),
                "party":     _wl(entry.get("parties")),
                "appointer": entry.get("appointer"),
                "notes":     str(entry.get("notes")).strip() if _has(entry.get("notes")) else "",
            })
    return problems


def sections(title: dict) -> list[dict]:
    """The parts a title's holder list is split into: one per seat, one per
    period, or a single unnamed one."""
    out = []
    for s in title.get("seats") or []:
        if not isinstance(s, dict) or not _has(s.get("for")):
            continue
        out.append({"heading": _text(s.get("name")) or f"{title['name']} for {_name(s.get('for'))}",
                    "seat": _name(s.get("for")),
                    "start": None, "end": None,
                    "max_holders": _year(s.get("max_holders")) or _year(title.get("max_holders")) or BIG})
    if out:
        return out
    for s in title.get("subtitles") or []:
        if not isinstance(s, dict):
            continue
        out.append({"heading": _text(s.get("name")) or title["name"],
                    "seat": None,
                    "start": _year(s.get("start_year")), "end": _year(s.get("end_year")),
                    "max_holders": _year(s.get("max_holders")) or _year(title.get("max_holders")) or BIG})
    if out:
        return out
    # No max_holders means no limit: a body, not a seat.
    return [{"heading": None, "seat": None, "start": None, "end": None,
             "max_holders": _year(title.get("max_holders")) or BIG}]


def place(holding, parts: list[dict]) -> dict | None:
    """Which section a term belongs to: its seat, or the period it overlaps most."""
    if holding["seat"]:
        for p in parts:
            if p["seat"] and p["seat"].casefold() == holding["seat"].casefold():
                return p
        return None
    dated = [p for p in parts if p["seat"] is None]
    if len(dated) == 1:
        return dated[0]
    start = holding["start"]
    if start is None:
        return dated[0] if dated else None
    end = holding["end"] if holding["end"] is not None else start
    best, best_overlap = None, None
    for p in dated:
        a = p["start"] if p["start"] is not None else -BIG
        b = p["end"] if p["end"] is not None else BIG
        overlap = min(end, b) - max(start, a)
        if best_overlap is None or overlap > best_overlap:
            best, best_overlap = p, overlap
    return best if best_overlap is not None and best_overlap >= 0 else None


def interludes_of(title: dict, part: dict) -> list[dict]:
    """The interludes that fall inside a section, as rows."""
    rows = []
    for i in title.get("interludes") or []:
        if not isinstance(i, dict):
            continue
        start, end = _year(i.get("start_year")), _year(i.get("end_year"))
        if part["seat"] is not None:
            continue
        a = part["start"] if part["start"] is not None else -BIG
        b = part["end"] if part["end"] is not None else BIG
        if start is not None and not (a <= start <= b):
            continue
        label = INTERLUDE_LABELS.get(str(i.get("kind") or "").strip().lower(), "Interlude")
        what = _text(i.get("name"))
        rows.append({"interlude": True, "label": f"*{what or label}*",
                     "kind": str(i.get("kind") or "").strip().lower(),
                     "start": start, "end": end,
                     "notes": str(i.get("notes")).strip() if _has(i.get("notes")) else ""})
    return rows


# ── Rendering ─────────────────────────────────────────────────────────────────

def _term(row) -> str:
    start = row["start"] if row["start"] is not None else "?"
    end = row["end"] if row["end"] is not None else "?"
    return f"{start} - {end}"


def render_part(title: dict, part: dict, holdings: list[dict], problems: list[str]) -> list[str]:
    dated = sorted((h for h in holdings if h["start"] is not None),
                   key=lambda h: (h["start"], h["end"] if h["end"] is not None else BIG, h["holder"]))
    undated = sorted((h for h in holdings if h["start"] is None), key=lambda h: h["holder"])
    numbered = title.get("numbered") is not False and part["max_holders"] == 1

    # More holders at once than the title allows is either canon, when a
    # disputed interlude covers those years, or something to fix.
    disputed = [(i["start"] if i["start"] is not None else -BIG,
                 i["end"] if i["end"] is not None else BIG)
                for i in interludes_of(title, part) if i["kind"] == "disputed"]
    for h in dated:
        at_once = [o for o in dated
                   if o is not h
                   and o["start"] < (h["end"] if h["end"] is not None else BIG)
                   and h["start"] < (o["end"] if o["end"] is not None else BIG)]
        if len(at_once) + 1 > part["max_holders"]:
            covered = any(a <= h["start"] <= b for a, b in disputed)
            if not covered:
                others = ", ".join(sorted({o["holder"] for o in at_once}))
                problems.append(f"{title['name']}"
                                + (f" ({part['heading']})" if part["heading"] else "")
                                + f": {h['holder']} holds it with {others}, "
                                  f"above max_holders {part['max_holders']}")

    rows_src = dated + undated + interludes_of(title, part)
    rows_src.sort(key=lambda r: (r["start"] if r["start"] is not None else BIG,
                                 r["end"] if r["end"] is not None else BIG))

    appointers = [h.get("appointer") for h in rows_src if _has(h.get("appointer"))]
    show_party = any(h.get("party") for h in rows_src)
    show_appt  = bool(appointers)
    appt_head  = "Election" if appointers and all(_is_election(a) for a in appointers) else "Appointed by"
    show_notes = any(h.get("notes") for h in rows_src)

    head = (["No."] if numbered else []) + ["Name", "Term"]
    head += (["Party"] if show_party else []) + ([appt_head] if show_appt else [])
    head += ["Notes"] if show_notes else []

    rows, number, prev_holder = [], 0, None
    for h in rows_src:
        cells = []
        if h.get("interlude"):
            cells = ([""] if numbered else []) + [h["label"], _term(h)]
            cells += ([""] if show_party else []) + ([""] if show_appt else [])
            cells += ([h["notes"]] if show_notes else [])
            rows.append([_cell(c) for c in cells])
            prev_holder = None
            continue
        if numbered:
            if h["start"] is None:
                cells.append("")
            elif h["holder"] != prev_holder:
                number += 1
                cells.append(str(number))
            else:
                cells.append("-")
        cells += [f"[[{h['holder']}]]", _term(h)]
        if show_party:
            cells.append(h["party"])
        if show_appt:
            cells.append(_wl(h.get("appointer")))
        if show_notes:
            cells.append(h.get("notes", ""))
        rows.append([_cell(c) for c in cells])
        if h["start"] is not None:
            prev_holder = h["holder"]

    if not rows:
        return []
    out = []
    if part["heading"]:
        years = ""
        if part["seat"] is None and (part["start"] is not None or part["end"] is not None):
            years = f" ({part['start'] or '?'} - {part['end'] or 'present'})"
        out += [f"### {part['heading']}{years}", ""]
    out += ["| " + " | ".join(head) + " |",
            "| " + " | ".join(":-:" if c in ("No.", "Term") else "---" for c in head) + " |"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    out += [""]
    return out


def render(title: dict, problems: list[str]) -> str:
    parts = sections(title)
    body = []
    for part in parts:
        holdings = [h for h in title["holdings"] if place(h, parts) is part]
        body += render_part(title, part, holdings, problems)
    for h in title["holdings"]:
        if place(h, parts) is None:
            problems.append(f"{title['name']}: {h['holder']}'s term "
                            f"({h['start']} to {h['end']}) fits no seat or period")
    if not body:
        body = ["*No holders recorded yet.*", ""]
    return "\n".join(body).rstrip("\n")


def write_into(title: dict, table: str) -> str:
    """Replace what lies between the marker lines. Nothing else is touched."""
    path = title["path"]
    text = path.read_text(encoding="utf-8-sig", errors="replace")
    block = f"{START}\n\n{table}\n\n{END}"
    if START in text and END in text:
        before, rest = text.split(START, 1)
        _, after = rest.split(END, 1)
        new = before + block + after
    else:
        new = text.rstrip("\n") + "\n\n" + block + "\n"
    if new != text:
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(new)
        return "written"
    return "unchanged"


# ── Universities and their alumni ─────────────────────────────────────────────

A_START = "%% alumni:start %%"
A_END   = "%% alumni:end %%"


def load_universities() -> dict:
    """name -> university article, for every note with type: university."""
    unis = {}
    for md in sorted(VAULT_ROOT.rglob("*.md")):
        rel = md.relative_to(VAULT_ROOT)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        if rel.parts[0] == "00 - Meta":
            continue  # the template itself
        fm = read_frontmatter(md)
        if fm.get("type") == "university":
            unis[md.stem] = {"path": md, "name": md.stem, "alumni": [], "fm": fm}
    return unis


def collect_alumni(unis: dict) -> list[str]:
    """Read every person's education entries into the university they name."""
    problems = []
    for md in sorted(VAULT_ROOT.rglob("*.md")):
        rel = md.relative_to(VAULT_ROOT)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        fm = read_frontmatter(md)
        if fm.get("type") != "person":
            continue
        for entry in fm.get("education") or []:
            if not isinstance(entry, dict) or not _has(entry.get("institution")):
                continue
            name = _name(entry["institution"])
            uni = unis.get(name)
            if uni is None:
                continue  # schools without a university article are fine
            uni["alumni"].append({
                "person": md.stem,
                "degree": _text(entry.get("degree")),
                "year":   _year(entry.get("year")),
            })
    return problems


def render_alumni(uni: dict) -> str:
    rows = sorted(uni["alumni"],
                  key=lambda a: (a["year"] if a["year"] is not None else BIG, a["person"]))
    if not rows:
        return "*No alumni recorded yet.*"
    out = ["| Name | Degree | Year |", "| --- | --- | :-: |"]
    for a in rows:
        year = str(a["year"]) if a["year"] is not None else "?"
        out.append(f"| {_cell('[[' + a['person'] + ']]')} | {_cell(a['degree'])} | {year} |")
    return "\n".join(out)


def write_alumni(uni: dict, table: str) -> str:
    path = uni["path"]
    text = path.read_text(encoding="utf-8-sig", errors="replace")
    block = f"{A_START}\n\n{table}\n\n{A_END}"
    if A_START in text and A_END in text:
        before, rest = text.split(A_START, 1)
        _, after = rest.split(A_END, 1)
        new = before + block + after
    else:
        new = text.rstrip("\n") + "\n\n## Alumni\n\n" + block + "\n"
    if new != text:
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(new)
        return "written"
    return "unchanged"


# ── University lists ──────────────────────────────────────────────────────────

U_START = "%% universities:start %%"
U_END   = "%% universities:end %%"
# index article -> country filter (None = every university)
UNIVERSITY_LISTS = {
    "List of susian universities": "Susia",
    "List of universities": None,
}


def load_cities() -> dict:
    cities = {}
    for md in sorted(VAULT_ROOT.rglob("*.md")):
        rel = md.relative_to(VAULT_ROOT)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        fm = read_frontmatter(md)
        # any place a university can sit in: cities, FEZs, etc.
        if _has(fm.get("country")) or _has(fm.get("state")):
            cities[md.stem] = fm
    return cities


def render_university_list(unis: dict, cities: dict, country) -> str:
    rows = []
    for name, uni in unis.items():
        fm = uni["fm"]
        city = _name(fm.get("seat"))
        cfm = cities.get(city, {})
        c = _name(cfm.get("country"))
        if country and c.casefold() != country.casefold():
            continue
        nature = fm.get("nature")
        nature = ", ".join(str(n) for n in nature if _has(n)) if isinstance(nature, list) else _text(nature)
        rows.append({"name": name, "city": _wl(city), "state": _wl(_name(cfm.get("state"))),
                     "country": _wl(c), "type": nature, "control": _wl(fm.get("control")),
                     "founded": _year(fm.get("founded"))})
    rows.sort(key=lambda r: (r["founded"] if r["founded"] is not None else BIG, r["name"]))
    if not rows:
        return "*No universities recorded yet.*"
    head = ["School", "City", "State" if country else "Country", "Type", "Control", "Founded"]
    out = ["| " + " | ".join(head) + " |",
           "| " + " | ".join(":-:" if h == "Founded" else "---" for h in head) + " |"]
    for r in rows:
        cells = [f"[[{r['name']}]]", r["city"], r["state"] if country else r["country"],
                 r["type"], r["control"], str(r["founded"]) if r["founded"] is not None else "?"]
        out.append("| " + " | ".join(_cell(x) for x in cells) + " |")
    return "\n".join(out)


def write_university_lists(unis: dict) -> None:
    cities = load_cities()
    for md in sorted(VAULT_ROOT.rglob("*.md")):
        rel = md.relative_to(VAULT_ROOT)
        if any(part in SKIP_DIRS for part in rel.parts) or md.stem not in UNIVERSITY_LISTS:
            continue
        text = md.read_text(encoding="utf-8-sig", errors="replace")
        if U_START not in text or U_END not in text:
            continue
        table = render_university_list(unis, cities, UNIVERSITY_LISTS[md.stem])
        before, rest = text.split(U_START, 1)
        _, after = rest.split(U_END, 1)
        new = before + f"{U_START}\n\n{table}\n\n{U_END}" + after
        if new != text:
            with open(md, "w", encoding="utf-8", newline="\n") as f:
                f.write(new)
        print(f"  {md.stem}: {'written' if new != text else 'unchanged'}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    titles = load_titles()
    if not titles:
        print("No title articles found.")
    problems = collect(titles)

    written = 0
    for name in sorted(titles):
        title = titles[name]
        state = write_into(title, render(title, problems))
        holders = len({h["holder"] for h in title["holdings"]})
        print(f"  {name}: {holders} holder(s), {state}")
        written += state == "written"

    unis = load_universities()
    problems += collect_alumni(unis)
    uni_written = 0
    for name in sorted(unis):
        uni = unis[name]
        state = write_alumni(uni, render_alumni(uni))
        print(f"  {name}: {len(uni['alumni'])} alumnus/alumni, {state}")
        uni_written += state == "written"
    print(f"University articles updated: {uni_written} of {len(unis)}.")
    write_university_lists(unis)

    # The old list articles belong to this script's previous shape.
    if LISTS_DIR.is_dir():
        for path in sorted(LISTS_DIR.glob("*.md")):
            try:
                owned = OLD_SENTINEL in path.read_text(encoding="utf-8-sig", errors="replace")
            except OSError:
                owned = False
            if owned:
                path.unlink()
                print(f"  removed Lists/{path.name}: holders live on the title article now")
        if not any(LISTS_DIR.iterdir()):
            LISTS_DIR.rmdir()

    for p in problems:
        print(f"warning: {p}", file=sys.stderr)
    print(f"Title articles updated: {written} of {len(titles)}; {len(problems)} problem(s).")


if __name__ == "__main__":
    main()
